{
 "title": "System Resources",
 "tags": [
  "aitransaction",
  "system"
 ],
 "refresh": "10s",
 "panels": [
  {
   "title": "GC Collections",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(process_runtime_dotnet_gc_collections_count_total[5m])",
     "legendFormat": "{{generation}} - {{job}}"
    }
   ]
  },
  {
   "title": "Memory Allocations",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(process_runtime_dotnet_gc_allocations_size_bytes_total[5m])",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "HTTP Client Requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(http_client_request_duration_seconds_count[5m])) by (job)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Active Requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    { "expr": "http_server_active_requests", "legendFormat": "{{job}}" }
   ]
  }
 ]
}